// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlLpWRL6FS4FK0fR7CxenUQQLyQHIZyc',
    appId: '1:1037639327100:web:ba88488cd6ae430044d8f9',
    messagingSenderId: '1037639327100',
    projectId: 'red-balloon-app',
    authDomain: 'red-balloon-app.firebaseapp.com',
    storageBucket: 'red-balloon-app.firebasestorage.app',
    measurementId: 'G-QE145NZL5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-8afUTWDCdxYvN8m2IVfI6c-9I75Sxpk',
    appId: '1:1037639327100:android:57de098d06f3922d44d8f9',
    messagingSenderId: '1037639327100',
    projectId: 'red-balloon-app',
    storageBucket: 'red-balloon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBadinHeHiw_filnu9u8C5RQEBxHA0drc',
    appId: '1:1037639327100:ios:743c4397b516281244d8f9',
    messagingSenderId: '1037639327100',
    projectId: 'red-balloon-app',
    storageBucket: 'red-balloon-app.firebasestorage.app',
    iosBundleId: 'com.redballoon.app',
  );
}
